# SPDX-FileCopyrightText: 2023 Thomas Breitner
#
# SPDX-License-Identifier: CC0-1.0

repos:
  - repo: https://github.com/fsfe/reuse-tool
    rev: v2.1.0
    hooks:
      - id: reuse
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: ''  # Use the sha / tag you want to point at
    hooks:
      - id: mypy
